# .platform.app.yaml
name: app

type: php:8.1 # Specify your PHP version

web:
  locations:
    "/":
      root: "public" # Update this to the directory containing index.php
      passthru: "/index.php"

disk: 1024 # Storage space for the app

relationships:
  database: "mysql:mysql"

dependencies:
  php:
    ext-pdo: "*"
    ext-mysqli: "*"

hooks:
  build: |
    composer install --no-dev --optimize-autoloader
  deploy: |
    echo "Deploying application..."
# .platform.app.yaml
name: app

type: php:8.1 # Specify your PHP version

web:
  locations:
    "/":
      root: "public" # Update this to the directory containing index.php
      passthru: "/index.php"

disk: 1024 # Storage space for the app

relationships:
  database: "mysql:mysql"

dependencies:
  php:
    ext-pdo: "*"
    ext-mysqli: "*"

hooks:
  build: |
    composer install --no-dev --optimize-autoloader
  deploy: |
    echo "Deploying application..."
